title: Dolls and Action Figures
description: Useful information.
url: "https://mister-funable.github.io/"
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
kramdown:
  toc_levels: 2..3

social:
  github: https://github.com/Mister-Funable
